name: nightly Publish Docker Image

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Get the date
        run: echo "TODAY=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Build and push Docker image with `latest` tag and nightly tag
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: yangclivia/one-api:latest, yangclivia/one-api:nightly-${{ env.TODAY }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha, prefix=one-api
          cache-to: type=gha, prefix=one-api, mode=max
